version: '1.0'
services:
  mongodb-server:
    image: mongo
    volumes:
      - ./data/db:/data/db
      
  auth-server:
    build: ./auth-server/app
    ports:
      - "3001:3001"
    volumes:
      - ./auth-server/app/src:/app/src
  